"""initial schema

Revision ID: 90aaab2a0b69
Revises: 
Create Date: 2026-09-22 17:11:26.925399+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '90aaab2a0b69'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_events_doc_id'), 'document_events', ['doc_id'], unique=False)
    op.create_table('document_facets',
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('facet', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('doc_id', 'facet', 'value')
    )
    op.create_index('ix_document_facets_fv', 'document_facets', ['facet', 'value'], unique=False)
    op.create_table('documents',
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('blob_uri', sa.Text(), nullable=True),
    sa.Column('version_key', sa.String(length=80), nullable=False),
    sa.Column('indexed_version', sa.String(length=80), nullable=True),
    sa.Column('tags_hash', sa.String(length=64), nullable=True),
    sa.Column('indexed_tags_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedding_fp', sa.String(length=16), nullable=True),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('last_seen_run_id', sa.String(length=40), nullable=True),
    sa.Column('tracking_id', sa.String(length=40), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('doc_id'),
    sa.UniqueConstraint('tracking_id')
    )
    op.create_index('ix_documents_review', 'documents', ['review_status'], unique=False)
    op.create_index('ix_documents_run_status', 'documents', ['run_id', 'status'], unique=False)
    op.create_index('ix_documents_source_status', 'documents', ['source_id', 'status'], unique=False)
    op.create_index('ix_documents_status_updated', 'documents', ['status', 'updated_at'], unique=False)
    op.create_table('ingest_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=160), nullable=False),
    sa.Column('lane', sa.String(length=16), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('visible_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_count', sa.Integer(), nullable=False),
    sa.Column('dead_lettered', sa.Boolean(), nullable=False),
    sa.Column('dl_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_ingest_queue_dead_lettered'), 'ingest_queue', ['dead_lettered'], unique=False)
    op.create_index(op.f('ix_ingest_queue_lane'), 'ingest_queue', ['lane'], unique=False)
    op.create_index(op.f('ix_ingest_queue_visible_at'), 'ingest_queue', ['visible_at'], unique=False)
    op.create_table('ingestion_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered', sa.Integer(), nullable=False),
    sa.Column('queued', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_ingestion_runs_source_id'), 'ingestion_runs', ['source_id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_started_at'), 'ingestion_runs', ['started_at'], unique=False)
    op.create_table('search_chunks',
    sa.Column('index_name', sa.String(length=128), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('doc_version', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('index_name', 'chunk_id')
    )
    op.create_index(op.f('ix_search_chunks_doc_id'), 'search_chunks', ['doc_id'], unique=False)
    op.create_table('search_indexes',
    sa.Column('index_name', sa.String(length=128), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_indexes')
    op.drop_index(op.f('ix_search_chunks_doc_id'), table_name='search_chunks')
    op.drop_table('search_chunks')
    op.drop_index(op.f('ix_ingestion_runs_started_at'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_source_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('ingestion_controls')
    op.drop_index(op.f('ix_ingest_queue_visible_at'), table_name='ingest_queue')
    op.drop_index(op.f('ix_ingest_queue_lane'), table_name='ingest_queue')
    op.drop_index(op.f('ix_ingest_queue_dead_lettered'), table_name='ingest_queue')
    op.drop_table('ingest_queue')
    op.drop_index('ix_documents_status_updated', table_name='documents')
    op.drop_index('ix_documents_source_status', table_name='documents')
    op.drop_index('ix_documents_run_status', table_name='documents')
    op.drop_index('ix_documents_review', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_document_facets_fv', table_name='document_facets')
    op.drop_table('document_facets')
    op.drop_index(op.f('ix_document_events_doc_id'), table_name='document_events')
    op.drop_table('document_events')
    # ### end Alembic commands ###
